name: Update README with Repo List

on:
  schedule:
    - cron: "0 0 * * 1"   # runs every Monday at midnight
  workflow_dispatch:       # allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update README
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { data: repos } = await github.repos.listForUser({
              username: 'devakiran046',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });
            const repoList = repos.map(r => `- [${r.name}](${r.html_url})`).join('\n');
            const content = `# Hi, I'm Deva 👋\n\n## My Projects\n${repoList}`;
            fs.writeFileSync('README.md', content);

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with latest repos"
          git push
